apiVersion: apps/v1
kind: Deployment
metadata:
  name: bully-election
spec:
  replicas: 5
  selector:
    matchLabels:
      app: bully-election
  template:
    metadata:
      labels:
        app: bully-election
    spec:
      serviceAccountName: bully-election
      containers:
        - name: bully-election
          image: iskorotkov/bully-election:v0.1.0-alpha.26
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEVELOPMENT
              value: "1"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bully-election
  labels:
    app: bully-election
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bully-election
  labels:
    app: bully-election
rules:
  - verbs: ["list", "get"]
    apiGroups: [""]
    resources: ["pods"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bully-election
  labels:
    app: bully-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bully-election
subjects:
  - kind: ServiceAccount
    name: bully-election
